# Generated by Django 5.2.1 on 2025-06-03 07:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "NewsCategory",
                "verbose_name_plural": "NewsCategories",
            },
        ),
        migrations.CreateModel(
            name="NewsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Giới thiệu về trang tin tức"
                    ),
                ),
                (
                    "posts_per_page",
                    models.IntegerField(
                        default=12, help_text="Số bài viết hiển thị mỗi trang"
                    ),
                ),
                (
                    "show_categories",
                    models.BooleanField(
                        default=True, help_text="Hiển thị filter theo danh mục"
                    ),
                ),
            ],
            options={
                "verbose_name": "News Index Page",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="NewsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Mô tả ngắn hiển thị trên listing", max_length=255
                    ),
                ),
                ("content", wagtail.fields.RichTextField(blank=True)),
                (
                    "date_created",
                    models.DateField(blank=True, null=True, verbose_name="Ngày tạo"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_pages",
                        to="news.newscategory",
                    ),
                ),
                (
                    "intro_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "News Article",
                "verbose_name_plural": "News Articles",
            },
            bases=("wagtailcore.page",),
        ),
    ]
