# Generated by Django 5.2.1 on 2025-06-05 10:02

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_newspage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="related_posts",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Chọn tối đa 5 bài viết liên quan.",
                related_name="related_to",
                to="news.newspage",
                verbose_name="Bài viết liên quan",
            ),
        ),
    ]
