# Generated by Django 5.2.1 on 2025-06-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_newspage_related_posts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspage",
            name="description",
        ),
    ]
