# Generated by Django 5.2.1 on 2025-06-06 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_remove_newspage_description"),
        ("streams", "0011_remove_menuitem_link_menuitem_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="hero_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Chọn Hero Section cho bài viết này",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="streams.herosection",
                verbose_name="Hero Section",
            ),
        ),
    ]
