# Generated by Django 5.2.1 on 2025-06-12 04:44

import streams.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_alter_newspage_hero_section"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsindexpage",
            options={},
        ),
        migrations.RemoveField(
            model_name="newsindexpage",
            name="intro",
        ),
        migrations.RemoveField(
            model_name="newsindexpage",
            name="posts_per_page",
        ),
        migrations.RemoveField(
            model_name="newsindexpage",
            name="show_categories",
        ),
        migrations.AddField(
            model_name="newsindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero_section_2", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (streams.models.HeroSection,),
                        {},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "hero_cta_slider_section_block",
                                    "Hero section với CTA và slider",
                                ),
                                (
                                    "hero_title_section_block",
                                    "Hero section với tiêu đề)",
                                ),
                                ("hero_empty_section_block", "Hero section trống"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("hero_section_data", 0), ("layout", 1)]],
                        {},
                    ),
                },
            ),
        ),
    ]
