# Generated by Django 5.2.1 on 2025-06-13 03:45

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_alter_newsindexpage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MostViewedNewsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Danh sách bài viết xem nhiều nhất",
                        editable=False,
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dự án nổi bật",
                "verbose_name_plural": "Danh sách bài viết được xem nhiều nhất",
            },
        ),
        migrations.AlterModelOptions(
            name="newspage",
            options={
                "verbose_name": "Bài viết Tin Tức",
                "verbose_name_plural": "Bài viết Tin Tức",
            },
        ),
        migrations.CreateModel(
            name="MostViewedNewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.newspage"
                    ),
                ),
                (
                    "parent",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="news.mostviewednewslist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bài viết được xem nhiều nhất",
                "verbose_name_plural": "Danh sách bài viết được xem nhiều nhất",
            },
        ),
    ]
