# Generated by Django 5.2.1 on 2025-07-09 10:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0010_newspage_canonical_url_newspage_og_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 1),
                    ("paragraph", 3),
                    ("image", 6),
                    ("two_images", 9),
                    ("table", 10),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.StructBlock", [[("heading_text", 0)]], {}),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "anchor-identifier",
                                "h1",
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "required": True,
                        },
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("text", 2)]], {}),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Chọn hình ảnh", "required": True},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Chú thích cho hình ảnh",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("caption", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Chọn hình ảnh đầu tiên", "required": True},
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Chọn hình ảnh thứ hai", "required": True},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("image1", 7), ("image2", 8), ("caption", 5)]],
                        {},
                    ),
                    10: ("streams.blocks.CustomTableBlock", (), {}),
                },
            ),
        ),
    ]
