# Generated by Django 5.2.1 on 2025-07-12 07:07

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0011_alter_newspage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspage",
            name="related_posts",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Chọn tối đa 3 bài viết liên quan.",
                related_name="related_to",
                to="news.newspage",
                verbose_name="Bài viết liên quan",
            ),
        ),
    ]
