# Generated by Django 5.2.1 on 2025-06-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_productindexpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productpage",
            name="price",
        ),
        migrations.AddField(
            model_name="productpage",
            name="product_code",
            field=models.CharField(default=2, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productpage",
            name="product_name",
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
