# Generated by Django 5.2.1 on 2025-06-11 07:22

import streams.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_remove_productpage_price_productpage_product_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero_section_2", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (streams.models.HeroSection,),
                        {},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "hero_cta_slider_section_block",
                                    "Hero section với CTA và slider",
                                ),
                                (
                                    "hero_title_section_block",
                                    "Hero section với tiêu đề)",
                                ),
                                ("hero_empty_section_block", "Hero section trống"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("hero_section_data", 0), ("layout", 1)]],
                        {},
                    ),
                },
            ),
        ),
    ]
