# Generated by Django 5.2.1 on 2025-06-10 03:26

import django.db.models.deletion
import streams.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("hero_section_2", 2), ("about_us_section", 12)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (streams.models.HeroSection,),
                                {},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        (
                                            "hero_cta_slider_section_block",
                                            "Hero section với CTA và slider",
                                        ),
                                        (
                                            "hero_title_section_block",
                                            "Hero section với tiêu đề)",
                                        ),
                                        (
                                            "hero_empty_section_block",
                                            "Hero section trống",
                                        ),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("hero_section_data", 0), ("layout", 1)]],
                                {},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Số liệu nổi bật (VD: 100+)",
                                    "required": True,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Mô tả ngắn về số liệu nổi bật (VD: Dự án đã hoàn thành)",
                                    "required": True,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("number", 3), ("description", 4)]],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.ListBlock",
                                (5,),
                                {
                                    "help_text": "Danh sách các số liệu nổi bật",
                                    "max_num": 4,
                                    "min_num": 1,
                                },
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Tiêu đề cho nhóm nội dung",
                                    "required": True,
                                },
                            ),
                            8: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                        "document-link",
                                        "image",
                                        "embed",
                                        "blockquote",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                        "code",
                                    ],
                                    "help_text": "Nội dung",
                                    "required": True,
                                },
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 7), ("content", 8)]],
                                {},
                            ),
                            10: (
                                "wagtail.blocks.ListBlock",
                                (9,),
                                {
                                    "help_text": "Danh sách các tiêu đề và nội dung",
                                    "max_num": 3,
                                    "min_num": 1,
                                },
                            ),
                            11: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Hình ảnh minh hoạ cho sứ mệnh",
                                    "required": True,
                                },
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("feature_items", 6),
                                        ("contents", 10),
                                        ("image", 11),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Trang về chúng tôi",
            },
            bases=("wagtailcore.page",),
        ),
    ]
