# Generated by Django 5.2.1 on 2025-07-07 04:23

import streams.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutUs", "0006_alter_aboutuspage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutuspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero_section_2", 2),
                    ("about_us_section", 12),
                    ("core_values_section", 18),
                    ("technology_section", 29),
                    ("partner_section", 37),
                    ("factory_section", 44),
                    ("we_are_dbhomes_section", 47),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (streams.models.HeroSection,),
                        {},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "hero_cta_slider_section_block",
                                    "Hero section với CTA và slider",
                                ),
                                (
                                    "hero_title_section_block",
                                    "Hero section với tiêu đề)",
                                ),
                                ("hero_empty_section_block", "Hero section trống"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("hero_section_data", 0), ("layout", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Số liệu nổi bật (VD: 100+)", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Mô tả ngắn về số liệu nổi bật (VD: Dự án đã hoàn thành)",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("number", 3), ("description", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.ListBlock",
                        (5,),
                        {
                            "help_text": "Danh sách các số liệu nổi bật",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề cho nhóm nội dung", "required": True},
                    ),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Nội dung",
                            "required": True,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("content", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {
                            "help_text": "Danh sách các tiêu đề và nội dung. Title thẻ h2",
                            "max_num": 3,
                            "min_num": 1,
                        },
                    ),
                    11: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh minh hoạ cho sứ mệnh",
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("feature_items", 6), ("contents", 10), ("image", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Phần chính của title. Thẻ h2",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Phần highlight của title sẽ có màu khác. Thẻ h2",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    15: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh biểu tượng (kích thước tối ưu 100x100px v.v)",
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("content", 8), ("icon", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (16,),
                        {
                            "help_text": "Danh sách các giá trị cốt lõi. Title thẻ h3, Content thẻ p",
                            "max_num": 6,
                            "min_num": 3,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("block1_title_main", 13),
                                ("block1_title_highlight", 14),
                                ("core_items", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "DB.Verse",
                            "help_text": "Phần highlight của title (VD: DB.Verse). Thẻ h3",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Theo dõi dự án trong lòng bàn tay",
                            "help_text": "Phần chính của title. Thẻ h3",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    21: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Đoạn văn đầu tiên",
                            "required": True,
                        },
                    ),
                    22: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh cho block 1 (phone mockup)",
                            "required": True,
                        },
                    ),
                    23: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://apps.apple.com",
                            "help_text": "Link App Store",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://play.google.com",
                            "help_text": "Link Google Play",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "DB.Verse",
                            "help_text": "Phần highlight của title block 2. Thẻ h3",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Theo dõi dự án trong lòng bàn tay",
                            "help_text": "Phần chính của title block 2. Thẻ h3",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    27: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Đoạn văn thứ hai",
                            "required": True,
                        },
                    ),
                    28: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh cho block 2 (user holding phone)",
                            "required": True,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("block1_title_highlight", 19),
                                ("block1_title_main", 20),
                                ("block1_paragraph1", 21),
                                ("block1_image", 22),
                                ("appstore_url", 23),
                                ("chplay_url", 24),
                                ("block2_title_highlight", 25),
                                ("block2_title_main", 26),
                                ("block2_paragraph", 27),
                                ("block2_image", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hình ảnh logo thương hiệu", "required": True},
                    ),
                    31: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Đường dẫn đến trang của thương hiệu",
                            "required": True,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 30), ("link", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.ListBlock",
                        (32,),
                        {"max_num": 7, "min_num": 1},
                    ),
                    34: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Tải lên video (.mp4, .mov)", "required": False},
                    ),
                    35: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Hoặc nhập link video YouTube/Vimeo",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("video_file", 34), ("video_url", 35)]],
                        {"help_text": "Ảnh hoặc video chính", "required": True},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("brands", 33), ("main_media", 36)]],
                        {},
                    ),
                    38: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hình ảnh nhà máy", "required": True},
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("content", 8)]],
                        {
                            "help_text": "Tiêu đề cho phần giới thiệu nhà máy. Title thẻ h2",
                            "required": True,
                        },
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Nhãn nút", "required": True},
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "Đường dẫn khi bấm",
                            "null": True,
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "Trang liên kết",
                            "null": True,
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 40), ("url", 41), ("page", 42)]],
                        {
                            "help_text": "Nút CTA cho phần giới thiệu nhà máy",
                            "required": True,
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 38), ("title", 39), ("button", 43)]],
                        {},
                    ),
                    45: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hình ảnh background", "required": True},
                    ),
                    46: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Nội dung giới thiệu về DBHomes",
                            "required": True,
                        },
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 45), ("content", 46)]],
                        {},
                    ),
                },
            ),
        ),
    ]
