# Generated by Django 5.2.1 on 2025-06-10 08:41

import streams.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero_section_2", 2),
                    ("about_us_section", 12),
                    ("core_values_section", 18),
                    ("technology_section", 28),
                    ("partner_section", 36),
                    ("qa_section", 42),
                    ("service_section", 51),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (streams.models.HeroSection,),
                        {},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "hero_cta_slider_section_block",
                                    "Hero section với CTA và slider",
                                ),
                                (
                                    "hero_title_section_block",
                                    "Hero section với tiêu đề)",
                                ),
                                ("hero_empty_section_block", "Hero section trống"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("hero_section_data", 0), ("layout", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Số liệu nổi bật (VD: 100+)", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Mô tả ngắn về số liệu nổi bật (VD: Dự án đã hoàn thành)",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("number", 3), ("description", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.ListBlock",
                        (5,),
                        {
                            "help_text": "Danh sách các số liệu nổi bật",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề cho nhóm nội dung", "required": True},
                    ),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Nội dung",
                            "required": True,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("content", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {
                            "help_text": "Danh sách các tiêu đề và nội dung",
                            "max_num": 3,
                            "min_num": 1,
                        },
                    ),
                    11: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh minh hoạ cho sứ mệnh",
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("feature_items", 6), ("contents", 10), ("image", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Theo dõi dự án trong lòng bàn tay",
                            "help_text": "Phần chính của title",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "DB.Verse",
                            "help_text": "Phần highlight của title sẽ có màu khác",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    15: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh biểu tượng (kích thước tối ưu 100x100px v.v)",
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("content", 8), ("icon", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (16,),
                        {
                            "help_text": "Danh sách các giá trị cốt lõi",
                            "max_num": 6,
                            "min_num": 3,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("block1_title_main", 13),
                                ("block1_title_highlight", 14),
                                ("core_items", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "DB.Verse",
                            "help_text": "Phần highlight của title (VD: DB.Verse)",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    20: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Đoạn văn đầu tiên",
                            "required": True,
                        },
                    ),
                    21: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh cho block 1 (phone mockup)",
                            "required": True,
                        },
                    ),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://apps.apple.com",
                            "help_text": "Link App Store",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://play.google.com",
                            "help_text": "Link Google Play",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "DB.Verse",
                            "help_text": "Phần highlight của title block 2",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Theo dõi dự án trong lòng bàn tay",
                            "help_text": "Phần chính của title block 2",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    26: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Đoạn văn thứ hai",
                            "required": True,
                        },
                    ),
                    27: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh cho block 2 (user holding phone)",
                            "required": True,
                        },
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("block1_title_highlight", 19),
                                ("block1_title_main", 13),
                                ("block1_paragraph1", 20),
                                ("block1_image", 21),
                                ("appstore_url", 22),
                                ("chplay_url", 23),
                                ("block2_title_highlight", 24),
                                ("block2_title_main", 25),
                                ("block2_paragraph", 26),
                                ("block2_image", 27),
                            ]
                        ],
                        {},
                    ),
                    29: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hình ảnh logo thương hiệu", "required": True},
                    ),
                    30: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Đường dẫn đến trang của thương hiệu",
                            "required": True,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 29), ("link", 30)]],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.ListBlock",
                        (31,),
                        {"max_num": 7, "min_num": 1},
                    ),
                    33: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Tải lên video (.mp4, .mov)", "required": False},
                    ),
                    34: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Hoặc nhập link video YouTube/Vimeo",
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("video_file", 33), ("video_url", 34)]],
                        {"help_text": "Ảnh hoặc video chính", "required": True},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("brands", 32), ("main_media", 35)]],
                        {},
                    ),
                    37: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hình ảnh trang trí", "required": True},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Câu hỏi", "required": True},
                    ),
                    39: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Câu trả lời",
                            "required": True,
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 38), ("answer", 39)]],
                        {},
                    ),
                    41: (
                        "wagtail.blocks.ListBlock",
                        (40,),
                        {
                            "help_text": "Danh sách các câu hỏi và câu trả lời",
                            "max_num": 5,
                            "min_num": 1,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 37), ("faq_items", 41)]],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Tiêu đề của phần dịch vụ", "required": True},
                    ),
                    44: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Mô tả ngắn về phần dịch vụ",
                            "required": True,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề dịch vụ", "required": True},
                    ),
                    46: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Nội dung mô tả dịch vụ",
                            "required": True,
                        },
                    ),
                    47: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh biểu tượng dịch vụ (kích thước tối ưu 100x100px)",
                            "required": True,
                        },
                    ),
                    48: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hình ảnh backgound khi hover", "required": True},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 45),
                                ("description", 46),
                                ("icon", 47),
                                ("hover_image", 48),
                            ]
                        ],
                        {},
                    ),
                    50: (
                        "wagtail.blocks.ListBlock",
                        (49,),
                        {
                            "help_text": "Danh sách các dịch vụ",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 43), ("description", 44), ("services", 50)]],
                        {},
                    ),
                },
            ),
        ),
    ]
