# Generated by Django 5.2.1 on 2025-05-30 03:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_homepage_options_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("nav_bar", 6), ("hero_section", 14)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Logo (hình ảnh)", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Alt text cho logo",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tên hiển thị", "required": True},
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Đường dẫn (có thể là internal hoặc external)",
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 2), ("link", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("logo_image", 0), ("logo_alt", 1), ("menu_items", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề chính hiển thị lớn", "required": True},
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    9: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {
                            "help_text": "Danh sách ảnh nền sẽ được hiển thị trong swiper"
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Nhãn nút", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Đường dẫn khi bấm", "required": True},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 10), ("url", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {"max_num": 3, "min_num": 0},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("background_images", 9), ("buttons", 13)]],
                        {},
                    ),
                },
            ),
        ),
    ]
