# Generated by Django 5.2.1 on 2025-05-30 08:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("nav_bar", 6),
                    ("hero_section", 14),
                    ("technology_section", 25),
                    ("partner_section", 34),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Logo (hình ảnh)", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Alt text cho logo",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tên hiển thị", "required": True},
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Đường dẫn (có thể là internal hoặc external)",
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 2), ("link", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("logo_image", 0), ("logo_alt", 1), ("menu_items", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề chính hiển thị lớn", "required": True},
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    9: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {
                            "help_text": "Danh sách ảnh nền sẽ được hiển thị trong swiper"
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Nhãn nút", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Đường dẫn khi bấm", "required": True},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 10), ("url", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {"max_num": 3, "min_num": 0},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("background_images", 9), ("buttons", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "DB.Verse",
                            "help_text": "Phần highlight của title (VD: DB.Verse)",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Theo dõi dự án trong lòng bàn tay",
                            "help_text": "Phần chính của title",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    17: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Đoạn văn đầu tiên",
                            "required": True,
                        },
                    ),
                    18: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh cho block 1 (phone mockup)",
                            "required": True,
                        },
                    ),
                    19: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://apps.apple.com",
                            "help_text": "Link App Store",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://play.google.com",
                            "help_text": "Link Google Play",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "DB.Verse",
                            "help_text": "Phần highlight của title block 2",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Theo dõi dự án trong lòng bàn tay",
                            "help_text": "Phần chính của title block 2",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    23: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Đoạn văn thứ hai",
                            "required": True,
                        },
                    ),
                    24: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh cho block 2 (user holding phone)",
                            "required": True,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("block1_title_highlight", 15),
                                ("block1_title_main", 16),
                                ("block1_paragraph1", 17),
                                ("block1_image", 18),
                                ("appstore_url", 19),
                                ("chplay_url", 20),
                                ("block2_title_highlight", 21),
                                ("block2_title_main", 22),
                                ("block2_paragraph", 23),
                                ("block2_image", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề của phần đối tác", "required": True},
                    ),
                    27: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hình ảnh logo thương hiệu", "required": True},
                    ),
                    28: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Đường dẫn đến trang của thương hiệu",
                            "required": True,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 27), ("link", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.ListBlock",
                        (29,),
                        {"max_num": 7, "min_num": 1},
                    ),
                    31: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Chọn ảnh nếu muốn hiển thị ảnh",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Hoặc nhập URL video (ví dụ YouTube)",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 31), ("video_url", 32)]],
                        {"help_text": "Ảnh hoặc video chính", "required": True},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 26), ("brands", 30), ("main_media", 33)]],
                        {},
                    ),
                },
            ),
        ),
    ]
