# Generated by Django 5.2.1 on 2025-06-02 03:44

import streams.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("nav_bar", 3),
                    ("hero_section", 11),
                    ("technology_section", 22),
                    ("partner_section", 31),
                    ("ecosystem_section", 34),
                    ("footer_section", 45),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Logo (hình ảnh)", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Alt text cho logo",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (streams.models.Menu,),
                        {
                            "help_text": "Chọn menu từ danh sách đã tạo",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("logo_image", 0), ("logo_alt", 1), ("menu_items", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề chính hiển thị lớn", "required": True},
                    ),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    6: (
                        "wagtail.blocks.ListBlock",
                        (5,),
                        {
                            "help_text": "Danh sách ảnh nền sẽ được hiển thị trong swiper"
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Nhãn nút", "required": True},
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Đường dẫn khi bấm", "required": True},
                    ),
                    9: ("wagtail.blocks.StructBlock", [[("label", 7), ("url", 8)]], {}),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {"max_num": 3, "min_num": 0},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("background_images", 6), ("buttons", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "DB.Verse",
                            "help_text": "Phần highlight của title (VD: DB.Verse)",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Theo dõi dự án trong lòng bàn tay",
                            "help_text": "Phần chính của title",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    14: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Đoạn văn đầu tiên",
                            "required": True,
                        },
                    ),
                    15: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh cho block 1 (phone mockup)",
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://apps.apple.com",
                            "help_text": "Link App Store",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://play.google.com",
                            "help_text": "Link Google Play",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "DB.Verse",
                            "help_text": "Phần highlight của title block 2",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Theo dõi dự án trong lòng bàn tay",
                            "help_text": "Phần chính của title block 2",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    20: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Đoạn văn thứ hai",
                            "required": True,
                        },
                    ),
                    21: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh cho block 2 (user holding phone)",
                            "required": True,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("block1_title_highlight", 12),
                                ("block1_title_main", 13),
                                ("block1_paragraph1", 14),
                                ("block1_image", 15),
                                ("appstore_url", 16),
                                ("chplay_url", 17),
                                ("block2_title_highlight", 18),
                                ("block2_title_main", 19),
                                ("block2_paragraph", 20),
                                ("block2_image", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề của phần đối tác", "required": True},
                    ),
                    24: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hình ảnh logo thương hiệu", "required": True},
                    ),
                    25: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Đường dẫn đến trang của thương hiệu",
                            "required": True,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 24), ("link", 25)]],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.ListBlock",
                        (26,),
                        {"max_num": 7, "min_num": 1},
                    ),
                    28: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Tải lên video (.mp4, .mov)", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Hoặc nhập link video YouTube/Vimeo",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("video_file", 28), ("video_url", 29)]],
                        {"help_text": "Ảnh hoặc video chính", "required": True},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 23), ("brands", 27), ("main_media", 30)]],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Tiêu đề của phần giới thiệu hệ sinh thái",
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Mô tả ngắn về hệ sinh thái",
                            "required": True,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 32), ("description", 33)]],
                        {},
                    ),
                    35: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Tải lên hồ sơ năng lực (.pdf)",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Logo mạng xã hội (hình ảnh kích thước 50x50px)",
                            "required": True,
                        },
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Alt text cho icon mạng xã hội",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    38: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Đường dẫn đến mạng xã hội", "required": True},
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("logo_image", 36), ("logo_alt", 37), ("link", 38)]],
                        {},
                    ),
                    40: (
                        "wagtail.blocks.ListBlock",
                        (39,),
                        {
                            "help_text": "Danh sách các mạng xã hội",
                            "max_num": 6,
                            "min_num": 1,
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tên văn phòng", "required": True},
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Địa chỉ văn phòng", "required": True},
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 41), ("address", 42)]],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.ListBlock",
                        (43,),
                        {
                            "help_text": "Danh sách các địa chỉ văn phòng",
                            "max_num": 3,
                            "min_num": 1,
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("capacity_profile", 35),
                                ("menu_items", 2),
                                ("follow_us", 40),
                                ("addresses", 44),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
