# Generated by Django 5.2.1 on 2025-06-09 04:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero_section", 7),
                    ("technology_section", 18),
                    ("partner_section", 27),
                    ("ecosystem_section", 30),
                    ("about_us_section", 40),
                    ("services_section", 49),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề chính hiển thị lớn", "required": True},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    2: (
                        "wagtail.blocks.ListBlock",
                        (1,),
                        {
                            "help_text": "Danh sách ảnh nền sẽ được hiển thị trong swiper"
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Nhãn nút", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Đường dẫn khi bấm", "required": True},
                    ),
                    5: ("wagtail.blocks.StructBlock", [[("label", 3), ("url", 4)]], {}),
                    6: ("wagtail.blocks.ListBlock", (5,), {"max_num": 3, "min_num": 0}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("background_images", 2), ("buttons", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "DB.Verse",
                            "help_text": "Phần highlight của title (VD: DB.Verse)",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Theo dõi dự án trong lòng bàn tay",
                            "help_text": "Phần chính của title",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Đoạn văn đầu tiên",
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh cho block 1 (phone mockup)",
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://apps.apple.com",
                            "help_text": "Link App Store",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://play.google.com",
                            "help_text": "Link Google Play",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "DB.Verse",
                            "help_text": "Phần highlight của title block 2",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Theo dõi dự án trong lòng bàn tay",
                            "help_text": "Phần chính của title block 2",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Đoạn văn thứ hai",
                            "required": True,
                        },
                    ),
                    17: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh cho block 2 (user holding phone)",
                            "required": True,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("block1_title_highlight", 8),
                                ("block1_title_main", 9),
                                ("block1_paragraph1", 10),
                                ("block1_image", 11),
                                ("appstore_url", 12),
                                ("chplay_url", 13),
                                ("block2_title_highlight", 14),
                                ("block2_title_main", 15),
                                ("block2_paragraph", 16),
                                ("block2_image", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề của phần đối tác", "required": True},
                    ),
                    20: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hình ảnh logo thương hiệu", "required": True},
                    ),
                    21: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Đường dẫn đến trang của thương hiệu",
                            "required": True,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 20), ("link", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {"max_num": 7, "min_num": 1},
                    ),
                    24: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Tải lên video (.mp4, .mov)", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Hoặc nhập link video YouTube/Vimeo",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("video_file", 24), ("video_url", 25)]],
                        {"help_text": "Ảnh hoặc video chính", "required": True},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 19), ("brands", 23), ("main_media", 26)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Tiêu đề của phần giới thiệu hệ sinh thái",
                            "required": True,
                        },
                    ),
                    29: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Mô tả ngắn về hệ sinh thái",
                            "required": True,
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 28), ("description", 29)]],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Nội dung giới thiệu về công ty",
                            "required": True,
                        },
                    ),
                    32: (
                        "wagtail.blocks.ListBlock",
                        (5,),
                        {
                            "help_text": "Danh sách các nút CTA",
                            "max_num": 2,
                            "min_num": 0,
                        },
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Số liệu nổi bật (VD: 100+)", "required": True},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Mô tả ngắn về số liệu nổi bật (VD: Dự án đã hoàn thành)",
                            "required": True,
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("number", 33), ("description", 34)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.ListBlock",
                        (35,),
                        {
                            "help_text": "Danh sách các số liệu nổi bật",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    37: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh nền (kích thước tối thiểu 1920x1080px)",
                            "required": True,
                        },
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Alt text cho hình nền", "required": False},
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 37), ("alt_text", 38)]],
                        {
                            "help_text": "Thiết lập hình nền cho section này",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("content", 31),
                                ("buttons", 32),
                                ("feature_items", 36),
                                ("background", 39),
                            ]
                        ],
                        {},
                    ),
                    41: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Tiêu đề của phần dịch vụ", "required": True},
                    ),
                    42: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Mô tả ngắn về phần dịch vụ",
                            "required": True,
                        },
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề dịch vụ", "required": True},
                    ),
                    44: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Nội dung mô tả dịch vụ",
                            "required": True,
                        },
                    ),
                    45: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh biểu tượng dịch vụ (kích thước tối ưu 100x100px)",
                            "required": True,
                        },
                    ),
                    46: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hình ảnh backgound khi hover", "required": True},
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 43),
                                ("description", 44),
                                ("icon", 45),
                                ("hover_image", 46),
                            ]
                        ],
                        {},
                    ),
                    48: (
                        "wagtail.blocks.ListBlock",
                        (47,),
                        {
                            "help_text": "Danh sách các dịch vụ",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 41), ("description", 42), ("services", 48)]],
                        {},
                    ),
                },
            ),
        ),
    ]
