# Generated by Django 5.2.1 on 2025-06-09 09:11

import streams.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero_section_2", 2),
                    ("technology_section", 13),
                    ("partner_section", 22),
                    ("ecosystem_section", 25),
                    ("about_us_section", 38),
                    ("services_section", 47),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (streams.models.HeroSection,),
                        {},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "hero_cta_slider_section_block",
                                    "Hero section với CTA và slider",
                                ),
                                (
                                    "hero_title_section_block",
                                    "Hero section với tiêu đề)",
                                ),
                                ("hero_empty_section_block", "Hero section trống"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("hero_section_data", 0), ("layout", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "DB.Verse",
                            "help_text": "Phần highlight của title (VD: DB.Verse)",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Theo dõi dự án trong lòng bàn tay",
                            "help_text": "Phần chính của title",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Đoạn văn đầu tiên",
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh cho block 1 (phone mockup)",
                            "required": True,
                        },
                    ),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://apps.apple.com",
                            "help_text": "Link App Store",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://play.google.com",
                            "help_text": "Link Google Play",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "DB.Verse",
                            "help_text": "Phần highlight của title block 2",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Theo dõi dự án trong lòng bàn tay",
                            "help_text": "Phần chính của title block 2",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Đoạn văn thứ hai",
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh cho block 2 (user holding phone)",
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("block1_title_highlight", 3),
                                ("block1_title_main", 4),
                                ("block1_paragraph1", 5),
                                ("block1_image", 6),
                                ("appstore_url", 7),
                                ("chplay_url", 8),
                                ("block2_title_highlight", 9),
                                ("block2_title_main", 10),
                                ("block2_paragraph", 11),
                                ("block2_image", 12),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề của phần đối tác", "required": True},
                    ),
                    15: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hình ảnh logo thương hiệu", "required": True},
                    ),
                    16: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Đường dẫn đến trang của thương hiệu",
                            "required": True,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 15), ("link", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (17,),
                        {"max_num": 7, "min_num": 1},
                    ),
                    19: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Tải lên video (.mp4, .mov)", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Hoặc nhập link video YouTube/Vimeo",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("video_file", 19), ("video_url", 20)]],
                        {"help_text": "Ảnh hoặc video chính", "required": True},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 14), ("brands", 18), ("main_media", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Tiêu đề của phần giới thiệu hệ sinh thái",
                            "required": True,
                        },
                    ),
                    24: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Mô tả ngắn về hệ sinh thái",
                            "required": True,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 23), ("description", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Nội dung giới thiệu về công ty",
                            "required": True,
                        },
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Nhãn nút", "required": True},
                    ),
                    28: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Đường dẫn khi bấm", "required": True},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 27), ("url", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.ListBlock",
                        (29,),
                        {
                            "help_text": "Danh sách các nút CTA",
                            "max_num": 2,
                            "min_num": 0,
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Số liệu nổi bật (VD: 100+)", "required": True},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Mô tả ngắn về số liệu nổi bật (VD: Dự án đã hoàn thành)",
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("number", 31), ("description", 32)]],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.ListBlock",
                        (33,),
                        {
                            "help_text": "Danh sách các số liệu nổi bật",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    35: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh nền (kích thước tối thiểu 1920x1080px)",
                            "required": True,
                        },
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Alt text cho hình nền", "required": False},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 35), ("alt_text", 36)]],
                        {
                            "help_text": "Thiết lập hình nền cho section này",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("content", 26),
                                ("buttons", 30),
                                ("feature_items", 34),
                                ("background", 37),
                            ]
                        ],
                        {},
                    ),
                    39: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Tiêu đề của phần dịch vụ", "required": True},
                    ),
                    40: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Mô tả ngắn về phần dịch vụ",
                            "required": True,
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề dịch vụ", "required": True},
                    ),
                    42: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Nội dung mô tả dịch vụ",
                            "required": True,
                        },
                    ),
                    43: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh biểu tượng dịch vụ (kích thước tối ưu 100x100px)",
                            "required": True,
                        },
                    ),
                    44: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hình ảnh backgound khi hover", "required": True},
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 41),
                                ("description", 42),
                                ("icon", 43),
                                ("hover_image", 44),
                            ]
                        ],
                        {},
                    ),
                    46: (
                        "wagtail.blocks.ListBlock",
                        (45,),
                        {
                            "help_text": "Danh sách các dịch vụ",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 39), ("description", 40), ("services", 46)]],
                        {},
                    ),
                },
            ),
        ),
    ]
