# Generated by Django 5.2.1 on 2025-06-14 08:57

import streams.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero_section_2", 2),
                    ("hot_project_section", 8),
                    ("technology_section", 19),
                    ("partner_section", 27),
                    ("ecosystem_section", 30),
                    ("about_us_section", 44),
                    ("HotNews", 47),
                    ("customer_feedback_block", 54),
                    ("services_section", 63),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (streams.models.HeroSection,),
                        {},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "hero_cta_slider_section_block",
                                    "Hero section với CTA và slider",
                                ),
                                (
                                    "hero_title_section_block",
                                    "Hero section với tiêu đề)",
                                ),
                                ("hero_empty_section_block", "Hero section trống"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("hero_section_data", 0), ("layout", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề cho nhóm nội dung", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Nội dung",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("content", 4)]],
                        {"help_text": "Nội dung tiêu đề", "required": True},
                    ),
                    6: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["project.ProjectPage"], "required": True},
                    ),
                    7: (
                        "wagtail.blocks.ListBlock",
                        (6,),
                        {"help_text": "Chọn các dự án nổi bật"},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 5), ("projects", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "DB.Verse",
                            "help_text": "Phần highlight của title (VD: DB.Verse)",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Theo dõi dự án trong lòng bàn tay",
                            "help_text": "Phần chính của title",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Đoạn văn đầu tiên",
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh cho block 1 (phone mockup)",
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://apps.apple.com",
                            "help_text": "Link App Store",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://play.google.com",
                            "help_text": "Link Google Play",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "DB.Verse",
                            "help_text": "Phần highlight của title block 2",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Theo dõi dự án trong lòng bàn tay",
                            "help_text": "Phần chính của title block 2",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    17: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Đoạn văn thứ hai",
                            "required": True,
                        },
                    ),
                    18: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh cho block 2 (user holding phone)",
                            "required": True,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("block1_title_highlight", 9),
                                ("block1_title_main", 10),
                                ("block1_paragraph1", 11),
                                ("block1_image", 12),
                                ("appstore_url", 13),
                                ("chplay_url", 14),
                                ("block2_title_highlight", 15),
                                ("block2_title_main", 16),
                                ("block2_paragraph", 17),
                                ("block2_image", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hình ảnh logo thương hiệu", "required": True},
                    ),
                    21: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Đường dẫn đến trang của thương hiệu",
                            "required": True,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 20), ("link", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {"max_num": 7, "min_num": 1},
                    ),
                    24: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Tải lên video (.mp4, .mov)", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Hoặc nhập link video YouTube/Vimeo",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("video_file", 24), ("video_url", 25)]],
                        {"help_text": "Ảnh hoặc video chính", "required": True},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("brands", 23), ("main_media", 26)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Tiêu đề của phần giới thiệu hệ sinh thái",
                            "required": True,
                        },
                    ),
                    29: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Mô tả ngắn về hệ sinh thái",
                            "required": True,
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 28), ("description", 29)]],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Nội dung giới thiệu về công ty",
                            "required": True,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Nhãn nút", "required": True},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"blank": True, "help_text": "Đường dẫn khi bấm", "null": True},
                    ),
                    34: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"blank": True, "help_text": "Trang liên kết", "null": True},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 32), ("url", 33), ("page", 34)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.ListBlock",
                        (35,),
                        {
                            "help_text": "Danh sách các nút CTA",
                            "max_num": 2,
                            "min_num": 0,
                        },
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Số liệu nổi bật (VD: 100+)", "required": True},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Mô tả ngắn về số liệu nổi bật (VD: Dự án đã hoàn thành)",
                            "required": True,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("number", 37), ("description", 38)]],
                        {},
                    ),
                    40: (
                        "wagtail.blocks.ListBlock",
                        (39,),
                        {
                            "help_text": "Danh sách các số liệu nổi bật",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    41: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh nền (kích thước tối thiểu 1920x1080px)",
                            "required": True,
                        },
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Alt text cho hình nền", "required": False},
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 41), ("alt_text", 42)]],
                        {
                            "help_text": "Thiết lập hình nền cho section này",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("content", 31),
                                ("buttons", 36),
                                ("feature_items", 40),
                                ("background", 43),
                            ]
                        ],
                        {},
                    ),
                    45: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "max_num": 3,
                            "min_num": 3,
                            "page_type": ["news.NewsPage"],
                            "required": True,
                        },
                    ),
                    46: (
                        "wagtail.blocks.ListBlock",
                        (45,),
                        {"help_text": "Chọn 3 bài tin tức hiển thị"},
                    ),
                    47: ("wagtail.blocks.StructBlock", [[("news_list", 46)]], {}),
                    48: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hình ảnh avatar khách hàng", "required": True},
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tên khách hàng", "required": True},
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tên dự án", "required": True},
                    ),
                    51: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Feedback của khách hàng",
                            "required": True,
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("customer_avatar", 48),
                                ("customer_name", 49),
                                ("customer_project", 50),
                                ("customer_feedback", 51),
                            ]
                        ],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.ListBlock",
                        (52,),
                        {
                            "help_text": "Danh sách các feedback",
                            "max_num": 10,
                            "min_num": 1,
                        },
                    ),
                    54: ("wagtail.blocks.StructBlock", [[("feedbacks", 53)]], {}),
                    55: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Tiêu đề của phần dịch vụ", "required": True},
                    ),
                    56: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Mô tả ngắn về phần dịch vụ",
                            "required": True,
                        },
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề dịch vụ", "required": True},
                    ),
                    58: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Nội dung mô tả dịch vụ",
                            "required": True,
                        },
                    ),
                    59: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh biểu tượng dịch vụ (kích thước tối ưu 100x100px)",
                            "required": True,
                        },
                    ),
                    60: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hình ảnh backgound khi hover", "required": True},
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 57),
                                ("description", 58),
                                ("icon", 59),
                                ("hover_image", 60),
                            ]
                        ],
                        {},
                    ),
                    62: (
                        "wagtail.blocks.ListBlock",
                        (61,),
                        {
                            "help_text": "Danh sách các dịch vụ",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 55), ("description", 56), ("services", 62)]],
                        {},
                    ),
                },
            ),
        ),
    ]
