# Generated by Django 5.2.1 on 2025-06-12 08:41

import django.db.models.deletion
import modelcluster.fields
import streams.models
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("hero_section_2", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (streams.models.HeroSection,),
                                {},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        (
                                            "hero_cta_slider_section_block",
                                            "Hero section với CTA và slider",
                                        ),
                                        (
                                            "hero_title_section_block",
                                            "Hero section với tiêu đề)",
                                        ),
                                        (
                                            "hero_empty_section_block",
                                            "Hero section trống",
                                        ),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("hero_section_data", 0), ("layout", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.AlterModelOptions(
            name="designstyle",
            options={
                "verbose_name": "Danh sách phong cách thiết kế",
                "verbose_name_plural": "Danh sách phong cách thiết kế",
            },
        ),
        migrations.AlterModelOptions(
            name="projectscale",
            options={
                "verbose_name": "Danh sách quy mô dự án",
                "verbose_name_plural": "Danh sách quy mô dự án",
            },
        ),
        migrations.CreateModel(
            name="ProjectPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(help_text="Tên dự án", max_length=255),
                ),
                (
                    "project_location",
                    models.CharField(
                        help_text="Vị trí (Tên chung cư, chủ đầu tư vv)", max_length=255
                    ),
                ),
                ("project_acreage", models.IntegerField(help_text="Diện tích")),
                (
                    "hero_section",
                    wagtail.fields.StreamField(
                        [("hero_section", 2)],
                        block_lookup={
                            0: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (streams.models.HeroSection,),
                                {},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        (
                                            "hero_cta_slider_section_block",
                                            "Hero section với CTA và slider",
                                        ),
                                        (
                                            "hero_title_section_block",
                                            "Hero section với tiêu đề)",
                                        ),
                                        (
                                            "hero_empty_section_block",
                                            "Hero section trống",
                                        ),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("hero_section_data", 0), ("layout", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 1),
                            ("paragraph", 3),
                            ("image", 6),
                            ("two_images", 9),
                            ("table", 10),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.StructBlock",
                                [[("heading_text", 0)]],
                                {},
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                        "document-link",
                                        "image",
                                        "embed",
                                        "blockquote",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                        "code",
                                    ],
                                    "required": True,
                                },
                            ),
                            3: ("wagtail.blocks.StructBlock", [[("text", 2)]], {}),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Chọn hình ảnh", "required": True},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Chú thích cho hình ảnh",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Chọn hình ảnh đầu tiên",
                                    "required": True,
                                },
                            ),
                            8: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Chọn hình ảnh thứ hai",
                                    "required": True,
                                },
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("image1", 7), ("image2", 8), ("caption", 5)]],
                                {},
                            ),
                            10: ("streams.blocks.CustomTableBlock", (), {}),
                        },
                    ),
                ),
                (
                    "design_style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="design_style",
                        to="project.designstyle",
                    ),
                ),
                (
                    "intro_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "project_scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_scale",
                        to="project.projectscale",
                    ),
                ),
                (
                    "related_posts",
                    modelcluster.fields.ParentalManyToManyField(
                        help_text="Chọn tối đa 5 bài viết liên quan.",
                        related_name="related_to",
                        to="project.projectpage",
                        verbose_name="Bài viết liên quan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bài viết Dự Án",
                "verbose_name_plural": "Bài viết Dự Án",
            },
            bases=("wagtailcore.page",),
        ),
    ]
