# Generated by Django 5.2.1 on 2025-06-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_projectindexpage_alter_designstyle_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectpage",
            name="project_name",
        ),
    ]
