# Generated by Django 5.2.1 on 2025-06-12 08:55

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_remove_projectpage_project_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="related_posts",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Chọn tối đa 5 bài viết liên quan.",
                null=True,
                related_name="related_to",
                to="project.projectpage",
                verbose_name="Bài viết liên quan",
            ),
        ),
    ]
