# Generated by Django 5.2.1 on 2025-06-13 03:11

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_projectpage_related_posts"),
    ]

    operations = [
        migrations.CreateModel(
            name="MostViewedProjectList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Danh sách dự án nổi bật",
                        editable=False,
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="related_posts",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Chọn 3 bài viết liên quan.",
                null=True,
                related_name="related_to",
                to="project.projectpage",
                verbose_name="Bài viết liên quan",
            ),
        ),
        migrations.CreateModel(
            name="MostViewedProjectItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projectpage",
                    ),
                ),
                (
                    "parent",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="project.mostviewedprojectlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dự án nổi bật",
                "verbose_name_plural": "Danh sách dự án nổi bật",
            },
        ),
    ]
