# Generated by Django 5.2.1 on 2025-06-13 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_mostviewedprojectlist_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mostviewedprojectitem",
            options={
                "verbose_name": "Dự án nổi bật",
                "verbose_name_plural": "Danh sách dự án được xem nhiều nhất",
            },
        ),
        migrations.AlterModelOptions(
            name="mostviewedprojectlist",
            options={
                "verbose_name": "Dự án nổi bật",
                "verbose_name_plural": "Danh sách dự án được xem nhiều nhất",
            },
        ),
    ]
