# Generated by Django 5.2.1 on 2025-06-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_alter_mostviewedprojectitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mostviewedprojectitem",
            options={
                "verbose_name": "Dự án được xem nhiều nhất",
                "verbose_name_plural": "Danh sách dự án được xem nhiều nhất",
            },
        ),
        migrations.AlterModelOptions(
            name="mostviewedprojectlist",
            options={
                "verbose_name": "Dự án được xem nhiều nhất",
                "verbose_name_plural": "Danh sách dự án được xem nhiều nhất",
            },
        ),
        migrations.AlterField(
            model_name="mostviewedprojectlist",
            name="title",
            field=models.CharField(
                default="Dự án được xem nhiều nhất", editable=False, max_length=255
            ),
        ),
    ]
