# Generated by Django 5.2.1 on 2025-06-14 03:42

import django.db.models.deletion
import streams.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_alter_mostviewedprojectitem_options_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectHomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("hero_section_2", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (streams.models.HeroSection,),
                                {},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        (
                                            "hero_cta_slider_section_block",
                                            "Hero section với CTA và slider",
                                        ),
                                        (
                                            "hero_title_section_block",
                                            "Hero section với tiêu đề)",
                                        ),
                                        (
                                            "hero_empty_section_block",
                                            "Hero section trống",
                                        ),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("hero_section_data", 0), ("layout", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Trang Dự án",
                "verbose_name_plural": "Trang Dự án",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterModelOptions(
            name="projectindexpage",
            options={
                "verbose_name": "Trang Danh sách Dự án",
                "verbose_name_plural": "Trang Danh sách Dự án",
            },
        ),
    ]
