# Generated by Django 5.2.1 on 2025-07-15 04:16

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_alter_projectpage_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Loại dự án", max_length=255)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Loại dự án",
                "verbose_name_plural": "Loại dự án",
            },
        ),
        migrations.AddField(
            model_name="projectscale",
            name="parent",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_scale",
                to="project.projecttype",
            ),
        ),
    ]
