# Generated by Django 5.2.1 on 2025-07-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0011_projecttype_projectscale_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectscale",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
