# Generated by Django 5.2.1 on 2025-07-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0012_projectscale_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttype",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
