# Generated by Django 5.2.1 on 2025-07-17 03:12

import django.db.models.deletion
import streams.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0013_alter_projecttype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="project_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_type",
                to="project.projecttype",
            ),
        ),
        migrations.AlterField(
            model_name="projecthomepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero_section_2", 2), ("ProjectHomePageBlock", 11)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (streams.models.HeroSection,),
                        {},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "hero_cta_slider_section_block",
                                    "Hero section với CTA và slider",
                                ),
                                (
                                    "hero_title_section_block",
                                    "Hero section với tiêu đề)",
                                ),
                                ("hero_empty_section_block", "Hero section trống"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("hero_section_data", 0), ("layout", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tiêu đề cho nhóm nội dung", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                            ],
                            "help_text": "Nội dung",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("content", 4)]],
                        {
                            "help_text": "Tiêu đề cho phần giới thiệu danh mục project",
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tên danh mục", "required": True},
                    ),
                    7: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hình ảnh đại diện cho danh mục dự án",
                            "required": True,
                        },
                    ),
                    8: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("project.ProjectType",),
                        {},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("image", 7), ("project_type", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {
                            "help_text": "Danh sách các Danh mục dự án",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("items", 10)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="project_scale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_scale",
                to="project.projectscale",
            ),
        ),
    ]
