# Generated by Django 5.2.1 on 2025-06-02 07:38

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0001_initial"),
        ("wagtaildocs", "0014_alter_document_file_size"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact",
                    wagtail.fields.RichTextField(
                        help_text="Thông tin liên hệ", verbose_name="Thông tin liên hệ"
                    ),
                ),
                (
                    "capacity_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tải lên hồ sơ năng lực (.pdf)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                        verbose_name="Hồ sơ năng lực",
                    ),
                ),
                (
                    "menu_items",
                    models.ForeignKey(
                        help_text="Chọn menu từ danh sách đã tạo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streams.menu",
                        verbose_name="Menu Footer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Settings",
                "verbose_name_plural": "Footer Settings",
            },
        ),
        migrations.CreateModel(
            name="FooterOfficeAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Tên văn phòng",
                        max_length=200,
                        verbose_name="Tên văn phòng",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Địa chỉ văn phòng",
                        max_length=500,
                        verbose_name="Địa chỉ văn phòng",
                    ),
                ),
                (
                    "footer",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office_addresses",
                        to="streams.footersettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Office Address",
                "verbose_name_plural": "Office Addresses",
            },
        ),
        migrations.CreateModel(
            name="FooterSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "logo_alt",
                    models.CharField(
                        help_text="Alt text cho icon mạng xã hội",
                        max_length=255,
                        verbose_name="Alt text cho icon",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        help_text="Đường dẫn đến mạng xã hội", verbose_name="Đường dẫn"
                    ),
                ),
                (
                    "footer",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="streams.footersettings",
                    ),
                ),
                (
                    "logo_image",
                    models.ForeignKey(
                        help_text="Logo mạng xã hội (hình ảnh kích thước 50x50px)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailimages.image",
                        verbose_name="Logo mạng xã hội",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media Link",
                "verbose_name_plural": "Social Media Links",
            },
        ),
    ]
