# Generated by Django 5.2.1 on 2025-06-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0003_herosectionblock_herosectionbody"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herosectionbody",
            name="sort_order",
        ),
    ]
