# Generated by Django 5.2.1 on 2025-06-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0004_remove_herosectionbody_sort_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herosectionbody",
            name="hero_section_block",
        ),
        migrations.DeleteModel(
            name="HeroSectionBlock",
        ),
    ]
