# Generated by Django 5.2.1 on 2025-06-06 07:49

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0005_remove_herosectionbody_hero_section_block_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiImageHeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("simple", "Hero đơn giản (1 ảnh)"),
                            ("multi_image", "Hero nhiều ảnh"),
                            ("with_button", "Hero có nút CTA"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HeroWithCTASection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("simple", "Hero đơn giản (1 ảnh)"),
                            ("multi_image", "Hero nhiều ảnh"),
                            ("with_button", "Hero có nút CTA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("button_text", models.CharField(max_length=50)),
                ("button_link", models.URLField()),
                (
                    "background_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HeroImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "hero",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="streams.multiimageherosection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimpleHeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("simple", "Hero đơn giản (1 ảnh)"),
                            ("multi_image", "Hero nhiều ảnh"),
                            ("with_button", "Hero có nút CTA"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "background_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="HeroSectionBody",
        ),
    ]
