# Generated by Django 5.2.1 on 2025-06-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0006_multiimageherosection_herowithctasection_heroimage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="heroimage",
            name="hero",
        ),
        migrations.RemoveField(
            model_name="heroimage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="herowithctasection",
            name="background_image",
        ),
        migrations.RemoveField(
            model_name="simpleherosection",
            name="background_image",
        ),
        migrations.DeleteModel(
            name="MultiImageHeroSection",
        ),
        migrations.DeleteModel(
            name="HeroImage",
        ),
        migrations.DeleteModel(
            name="HeroWithCTASection",
        ),
        migrations.DeleteModel(
            name="SimpleHeroSection",
        ),
    ]
