# Generated by Django 5.2.1 on 2025-06-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0007_remove_heroimage_hero_remove_heroimage_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Tiêu đề của phần Hero",
                        max_length=255,
                        verbose_name="Tiêu đề",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
