# Generated by Django 5.2.1 on 2025-06-06 08:09

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0008_herosection"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="display_text",
            field=models.CharField(
                blank=True,
                help_text="Văn bản hiển thị trên phần Hero",
                max_length=255,
                null=True,
                verbose_name="Văn bản hiển thị",
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="is_have_cta",
            field=models.BooleanField(
                default=False,
                help_text="Chọn nếu phần Hero này sẽ có nút CTA",
                verbose_name="Có nút CTA",
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="is_multi_image",
            field=models.BooleanField(
                default=True,
                help_text="Chọn nếu phần Hero này sẽ hiển thị nhiều hình ảnh",
                verbose_name="Hiển thị nhiều hình ảnh",
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="title",
            field=models.CharField(
                help_text="Tên Hero", max_length=255, verbose_name="Tên Hero"
            ),
        ),
        migrations.CreateModel(
            name="CTA_Button",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Nhãn hiển thị trên nút CTA",
                        max_length=100,
                        verbose_name="Nhãn nút",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        help_text="Đường dẫn đến trang đích của nút CTA",
                        verbose_name="Đường dẫn",
                    ),
                ),
                (
                    "hero_section",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cta_buttons",
                        to="streams.herosection",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chọn trang liên kết đến nút CTA",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Trang liên kết",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HeroImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "alt_text",
                    models.CharField(
                        help_text="Văn bản thay thế cho hình ảnh",
                        max_length=255,
                        verbose_name="Alt text",
                    ),
                ),
                (
                    "hero_section",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_images",
                        to="streams.herosection",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Hình ảnh hiển thị trong phần Hero",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailimages.image",
                        verbose_name="Hình ảnh",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
