# Generated by Django 5.2.1 on 2025-06-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0009_herosection_display_text_herosection_is_have_cta_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="logo_alt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Alt text cho logo"
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="logo_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Logo (hình ảnh)",
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="is_multi_image",
            field=models.BooleanField(
                default=False,
                help_text="Chọn nếu phần Hero này sẽ hiển thị nhiều hình ảnh",
                verbose_name="Hiển thị nhiều hình ảnh",
            ),
        ),
    ]
