# Generated by Django 5.2.1 on 2025-06-06 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0010_menu_logo_alt_menu_logo_image_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="link",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="page",
            field=models.ForeignKey(
                blank=True,
                help_text="Chọn trang liên kết đến nút nav bar item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Trang liên kết",
            ),
        ),
    ]
