# Generated by Django 5.2.1 on 2025-06-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0011_remove_menuitem_link_menuitem_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cta_button",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Đường dẫn đến trang đích của nút CTA",
                null=True,
                verbose_name="Đường dẫn",
            ),
        ),
    ]
