# Generated by Django 5.2.1 on 2025-07-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0012_alter_cta_button_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herosection",
            name="display_text",
            field=models.CharField(
                blank=True,
                help_text="Văn bản hiển thị trên phần Hero. Thẻ h1",
                max_length=255,
                null=True,
                verbose_name="Văn bản hiển thị",
            ),
        ),
    ]
