# Generated by Django 5.2.1 on 2025-07-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0013_alter_herosection_display_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="footerofficeaddress",
            name="gmap_url",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
