# Generated by Django 5.2.1 on 2025-07-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0014_footerofficeaddress_gmap_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("call", "Gọi ngay"),
                            ("messenger", "Messenger"),
                            ("zalo", "Zalo"),
                            ("custom", "Tùy chỉnh khác"),
                        ],
                        default="custom",
                        max_length=50,
                        verbose_name="Loại nút",
                    ),
                ),
                ("url", models.URLField(verbose_name="Liên kết")),
                (
                    "label",
                    models.CharField(
                        default="", max_length=100, verbose_name="Nhãn hiển thị"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nút liên hệ",
                "verbose_name_plural": "Danh sách nút liên hệ",
            },
        ),
    ]
