# Generated by Django 5.2.1 on 2025-07-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0015_contactbutton"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactbutton",
            name="type",
            field=models.CharField(
                choices=[
                    ("call", "Gọi ngay"),
                    ("messenger", "Messenger"),
                    ("zalo", "Zalo"),
                ],
                default="custom",
                max_length=50,
                verbose_name="Loại nút",
            ),
        ),
        migrations.AlterField(
            model_name="contactbutton",
            name="url",
            field=models.CharField(max_length=255, verbose_name="Liên kết"),
        ),
    ]
